let port = "8080";
let cpf = "33682376160"; //alterar o cpf a cada teste novo
let cnpj = "41282196000131"; //alterar o cnpj a cada teste novo
let email = "te_st_de1a1q123@tep1ste.com.br" //alterar o email a cada teste novo

describe('Teste de criação de conta de cliente', () => {
  it('Cadastra um cliente novo', () => {
    cy.visit('http://localhost:' + port + '/trabalho-les/home')
    cy.wait(500)
    cy.get('[cypress-login]').click()
    cy.wait(500)
    cy.visit('http://localhost:' + port + '/trabalho-les/login')
    cy.wait(500)
    cy.get('[cypress-novaConta]').click()
    cy.wait(500)
    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/novaConta')
    cy.wait(500)

    cy.get('[cypress-submit]').click()
    cy.wait(500)

    cy.get('[cypress-nome]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-email]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-genero]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-tipoCliente]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-dataNascimento]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senha]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senhaConfirmar]').parent().should('have.class', 'has-danger')
    cy.wait(500)

    cy.get('[cypress-nome]').type('teste').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-genero').select('1').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-tipoCliente').select('1').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-dataNascimento').type('1988-03-12').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-email]').type('teste').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-email]').type('@').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-email]').type('teste').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-email]').type('.com').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-email]').clear().type(email)
    cy.wait(500)
    cy.get('[cypress-senha]').type('12').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senha]').type('e').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senha]').type('Mud').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senha]').type('!').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senha]').type('A!').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-senhaConfirmar]').type('algodiferente').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senhaConfirmar]').clear().type('12eMud!A!').parent().should('have.class', 'has-success')
    cy.wait(500)

    cy.get('[cypress-submit]').click().wait(500)

    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/novaConta')
    cy.wait(500)

    cy.get('[cypress-nome]').type('teste').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-genero').select('1').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-tipoCliente').select('1').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-dataNascimento').type('1988-03-12').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-email]').type(email).parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-senha]').type('123Mudar!').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-senhaConfirmar]').clear().type('123Mudar!').parent().should('have.class', 'has-success')
    cy.wait(500)

    cy.get('.js-tipo-documento').select('1')
    cy.wait(500)
    cy.get('.js-numero-documento').type(cpf)
    cy.wait(500)
    cy.get('.js-validade-documento').type('2022-03-31')
    cy.wait(500)
    cy.get('.js-adicionar-documento').click()
    cy.wait(500)
    cy.get('.js-boxes-documentos .box-single').should('be.visible')
    cy.wait(500)

    cy.get('.js-nome-endereco').type('Endereço Teste')
    cy.wait(500)
    cy.get('.js-tipo-endereco').select('1')
    cy.wait(500)
    cy.get('.js-tipo-residencia').select('1')
    cy.wait(500)
    cy.get('.js-funcao-endereco').select('1')
    cy.wait(500)
    cy.get('.js-pais').select('1')
    cy.wait(500)
    cy.get('.js-cep').type('12345678')
    cy.wait(500)
    cy.get('.js-tipo-logradouro').select('1')
    cy.wait(500)
    cy.get('.js-logradouro').type('Rua teste')
    cy.wait(500)
    cy.get('.js-numero').type('12')
    cy.wait(500)
    cy.get('.js-bairro').type('Vila Oliveira')
    cy.wait(500)
    cy.get('.js-cidade').type('Mogi das Cruzes')
    cy.wait(500)
    cy.get('.js-uf').type('SP')
    cy.wait(500)
    cy.get('.js-adicionar-endereco').click()
    cy.wait(500)
    cy.get('.js-boxes-enderecos .box-single').should('be.visible')
    cy.wait(500)

    cy.get('.js-nome-endereco').type('Endereço Teste')
    cy.wait(500)
    cy.get('.js-tipo-endereco').select('1')
    cy.wait(500)
    cy.get('.js-tipo-residencia').select('1')
    cy.wait(500)
    cy.get('.js-funcao-endereco').select('2')
    cy.wait(500)
    cy.get('.js-pais').select('1')
    cy.wait(500)
    cy.get('.js-cep').type('08780220')
    cy.wait(500)
    cy.get('.js-tipo-logradouro').select('1')
    cy.wait(500)
    cy.get('.js-logradouro').type('Rua teste')
    cy.wait(500)
    cy.get('.js-numero').type('12')
    cy.wait(500)
    cy.get('.js-bairro').type('Vila Oliveira')
    cy.wait(500)
    cy.get('.js-cidade').type('Mogi das Cruzes')
    cy.wait(500)
    cy.get('.js-uf').type('SP')
    cy.wait(500)
    cy.get('.js-adicionar-endereco').click()
    cy.wait(500)
    cy.get('.js-boxes-enderecos .box-single').should('be.visible')
    cy.wait(500)

    cy.get('.js-numero-cartao').type('1111222233334444')
    cy.wait(500)
    cy.get('.js-nome-cartao').type('Teste')
    cy.wait(500)
    cy.get('.js-bandeira-cartao').select('1')
    cy.wait(500)
    cy.get('.js-cvv-cartao').type('123')
    cy.wait(500)
    cy.get('.js-validade-cartao').type('2030-12-31')
    cy.wait(500)
    cy.get('.js-adicionar-cartao').click()
    cy.wait(500)
    cy.get('.js-boxes-cartoes .box-single').should('be.visible')
    cy.wait(500)
    cy.get('input[name="cartaoPreferencial"][value="1111222233334444"]').click()
    cy.wait(500)

    cy.get('.js-tipo-telefone').select('1')
    cy.wait(500)
    cy.get('.js-ddd-telefone').type('11')
    cy.wait(500)
    cy.get('.js-numero-telefone').type('56125678')
    cy.wait(500)
    cy.get('.js-adicionar-telefone').click()
    cy.wait(500)
    cy.get('.js-boxes-telefones .box-single').should('be.visible')
    cy.wait(500)

    cy.get('[cypress-submit]').click()
    cy.wait(500)

    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/home')
    cy.wait(500)
  });
});

describe('Teste de alteração de dados cadastrais do cliente', () => {
  it('Edita os dados do cliente', () => {
    cy.visit('http://localhost:' + port + '/trabalho-les/home')
    cy.wait(500)
    cy.get('[cypress-login]').click()
    cy.wait(500)
    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/login')
    cy.wait(500)

    cy.get('[cypress-email]').type(email)    
    cy.wait(600);
    cy.get('[cypress-senha]').type("123Mudar!")    
    cy.wait(600);
    cy.get('[cypress-submit]').click()    
    cy.wait(600);
    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/home')
    
    cy.wait(600);
    cy.get('[cypress-minhaConta]').click()
    cy.wait(500)

    cy.get('[cypress-alterarMeusDados]').click()
    cy.wait(500)
    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/alterarMeusDados')
    cy.wait(500)

    cy.get('[cypress-nome]').clear()
    cy.wait(500)
    cy.get('[cypress-email]').clear()
    cy.wait(500)
    cy.get('[cypress-genero]').select('')
    cy.wait(500)
    cy.get('[cypress-tipoCliente]').select('')
    cy.wait(500)
    cy.get('[cypress-dataNascimento]').clear()
    cy.wait(500)

    cy.get('[cypress-submit]').click()
    cy.wait(500)

    cy.get('[cypress-nome]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-email]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-genero]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-tipoCliente]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-dataNascimento]').parent().should('have.class', 'has-danger')
    cy.wait(500)

    cy.get('[cypress-nome]').type('teste').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-genero').select('1').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-tipoCliente').select('1').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-dataNascimento').type('1988-03-12').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-email]').type('teste').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-email]').type('@').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-email]').type('teste').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-email]').type('.com').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-email]').clear().type(email)

    cy.get('[cypress-submit]').click().wait(500)

    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/minhaConta')
    cy.wait(500)

    cy.get('[cypress-alterarMeusDados]').click()
    cy.wait(500)
    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/alterarMeusDados')
    cy.wait(500)

    cy.get('.js-tipo-documento').select('2')
    cy.wait(500)
    cy.get('.js-numero-documento').type(cnpj)
    cy.wait(500)
    cy.get('.js-validade-documento').type('2022-03-31')
    cy.wait(500)
    cy.get('.js-adicionar-documento').click()
    cy.wait(500)
    cy.get('.js-boxes-documentos .box-single').should('be.visible')
    cy.wait(500)

    cy.get('.js-nome-endereco').type('Endereço Teste')
    cy.wait(500)
    cy.get('.js-tipo-endereco').select('1')
    cy.wait(500)
    cy.get('.js-tipo-residencia').select('1')
    cy.wait(500)
    cy.get('.js-funcao-endereco').select('1')
    cy.wait(500)
    cy.get('.js-pais').select('1')
    cy.wait(500)
    cy.get('.js-cep').type('12345678')
    cy.wait(500)
    cy.get('.js-tipo-logradouro').select('1')
    cy.wait(500)
    cy.get('.js-logradouro').type('Rua teste')
    cy.wait(500)
    cy.get('.js-numero').type('12')
    cy.wait(500)
    cy.get('.js-bairro').type('Vila Oliveira')
    cy.wait(500)
    cy.get('.js-cidade').type('Mogi das Cruzes')
    cy.wait(500)
    cy.get('.js-uf').type('SP')
    cy.wait(500)
    cy.get('.js-adicionar-endereco').click()
    cy.wait(500)
    cy.get('.js-boxes-enderecos .box-single').should('be.visible')
    cy.wait(500)

    cy.get('.js-numero-cartao').type('1111222233334444')
    cy.wait(500)
    cy.get('.js-nome-cartao').type('Teste')
    cy.wait(500)
    cy.get('.js-bandeira-cartao').select('1')
    cy.wait(500)
    cy.get('.js-cvv-cartao').type('123')
    cy.wait(500)
    cy.get('.js-validade-cartao').type('2030-12-31')
    cy.wait(500)
    cy.get('.js-adicionar-cartao').click()
    cy.wait(500)
    cy.get('.js-boxes-cartoes .box-single').should('be.visible')
    cy.wait(500)

    cy.get('.js-tipo-telefone').select('2')
    cy.wait(500)
    cy.get('.js-ddd-telefone').type('11')
    cy.wait(500)
    cy.get('.js-numero-telefone').type('912345678')
    cy.wait(500)
    cy.get('.js-adicionar-telefone').click()
    cy.wait(500)
    cy.get('.js-boxes-telefones .box-single').should('be.visible')
    cy.wait(500)

    cy.get('[cypress-submit]').click()
    cy.wait(500)

    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/minhaConta')
    cy.wait(500)

    cy.get('[cypress-alterarMeusDados]').click()
    cy.wait(500)
    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/alterarMeusDados')
    cy.wait(500)

    cy.get('.js-boxes-enderecos .box-single:first-of-type .js-remove-existing-endereco').click()
    cy.wait(500)
    cy.get('.js-boxes-cartoes .box-single:first-of-type .js-remove-existing-cartao').click()
    cy.wait(500)
    cy.get('input[name="cartaoPreferencial"]').first().click()
    cy.wait(500)
    cy.get('.js-boxes-telefones .box-single:first-of-type .js-remove-existing-telefone').click()
    cy.wait(500)

    cy.get('[cypress-submit]').click()
    cy.wait(500)

    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/minhaConta')
    cy.wait(500)
  });

	it('Altera a senha do cliente', () => {
    cy.visit('http://localhost:' + port + '/trabalho-les/home')
    cy.wait(500)
    cy.get('[cypress-login]').click()
    cy.wait(500)
    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/login')
    cy.wait(500)

    cy.get('[cypress-email]').type(email)    
    cy.wait(600);
    cy.get('[cypress-senha]').type("123Mudar!")    
    cy.wait(600);
    cy.get('[cypress-submit]').click()    
    cy.wait(600);
    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/home')
    cy.wait(500)
    cy.get('[cypress-minhaConta]').click()
    cy.wait(500)
    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/minhaConta')
    cy.wait(500)

    cy.get('[cypress-alterarMinhaSenha]').click()
    cy.wait(500)
    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/alterarMinhaSenha')
    cy.wait(500)

    cy.get('[cypress-submit]').click()
    cy.wait(500)

    cy.get('[cypress-senhaAtual]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senhaNova]').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senhaConfirmar]').parent().should('have.class', 'has-danger')
    cy.wait(500)

    cy.get('[cypress-senhaAtual]').clear().type('123Mudar!').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-senhaNova]').type('12').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senhaNova]').type('e').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senhaNova]').type('Mud').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senhaNova]').type('!').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senhaNova]').type('A!').parent().should('have.class', 'has-success')
    cy.wait(500)
    cy.get('[cypress-senhaConfirmar]').type('algodiferente').parent().should('have.class', 'has-danger')
    cy.wait(500)
    cy.get('[cypress-senhaConfirmar]').clear().type('12eMud!A!').parent().should('have.class', 'has-success')
    cy.wait(500)

    cy.get('[cypress-submit]').click()
    cy.wait(500)

    cy.url().should('include', 'http://localhost:' + port + '/trabalho-les/minhaConta')
    cy.wait(500)
  });

});